<!DOCTYPE html>
<html lang="zh-TW">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>匯入資料 - 學測五選四</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	<script src="/cdn-cgi/apps/head/H8B_QeH_c85F2A0Pn-8BNHymBsQ.js"></script><link href="https://www.sean.taipei/assets/css/tocas-ui/tocas.css" rel="stylesheet">
	<link href="//cdn.rawgit.com/gnehs/Tocas-UI-Xiaoan/master/ts.xiaoan.min.css" rel="stylesheet">
	<link href="../style.css?v=1017" rel="stylesheet">
</head>
<body>
	<nav class="ts basic fluid borderless menu horizontally scrollable">
		<div class="ts container">
			<a class="item" href="/gsat">首頁</a>
			<a class="item hide1" href="../apply">個人申請</a>
			<a class="item hide1" href="../star">繁星推薦</a>
			<a class="item hide1" href="../advanced">指考分發</a>
			<div class="right fitted item">
				<img class="ts mini circular image" src="https://t.me/i/userpic/320/0xqDFO_DSo_O0jLPKUI54XCEbUDRumdWI_qpPAxPFj4.jpg">
				<b class="item">Sean</b>
			</div>
		</div>
	</nav>
	<header class="ts fluid vertically padded heading slate">
		<div class="ts narrow container">
			<h1 class="header">同步資料</h1>
			<div class="description">讓您跨平台同步「我的最愛」，也能即時分享給老師、同學們</div>
		</div>
	</header>
	<div class="ts container" name="main">
<?php
$key = $_GET['key'] ?? '';
if (!preg_match("#^[A-Za-z0-9_]{5,32}\-(10[89])(apply|star|advanced)\-[0-9a-f]{2,5}$#", $key)) {
	echo <<<EOF
<big style='color: red;'>網址格式錯誤，即將導向首頁</big>
<script>
	setTimeout(() => {
		location.href = '..';
	}, 3000);
</script>
EOF;
} else {
	echo <<<EOF
<h3>新增校系</h3>
<table id="addedFavs"></table>
<h3>刪除校系</h3>
<table id="deletedFavs"></table>
<h3>共同校系</h3>
<table id="commonFavs"></table>

<script>
	var key = "$key"; // Generated by server-side (GET param <keys>)
	var type = key.split('-')[1];
	var favStorageName = "favs" + type;

	var newFavs = loadConfig(key);

	var currentFavs = [];
	if (localStorage.getItem(favStorageName))
		currentFavs = JSON.parse(localStorage.getItem(favStorageName));
	if (!(currentFavs instanceof Array)) {
		console.error("Unknown type of currentFavs:", currentFavs);
		currentFavs = [];
	}

	console.log(newFavs, currentFavs);

	var addedFavs = [];
	var commonFavs = [];
	var deletedFavs = [];

	for (var k = 0; k < newFavs.length; k++) {
		var item = newFavs[k];
		if (currentFavs.indexOf(item) === -1)
			addedFavs.push(item);
		else
			commonFavs.push(item);
	}

	for (var k = 0; k < currentFavs.length; k++) {
		var item = currentFavs[k];
		if (newFavs.indexOf(item) === -1)
			deletedFavs.push(item);
	}


	genDiff("addedFavs", addedFavs);
	genDiff("deletedFavs", deletedFavs);
	genDiff("commonFavs", commonFavs);

	function loadConfig(key) {
		var data = new FormData();
		data.append("key", key);
		var xhr = new XMLHttpRequest();
		xhr.open("POST", "load", false);
		xhr.send(data);
		var resp = JSON.parse(xhr.response);
		var favs = resp.favs;
		return favs;
	}

	function genDiff(tableId, favs) {
		if (favs.length === 0)
			return;

		var table = document.getElementById(tableId);

		var tr = document.createElement('tr');
		for (var i = 0; i < 3; i++)
			tr.appendChild(document.createElement('th'));
		tr.cells[0].appendChild(document.createTextNode('學校'));
		tr.cells[1].appendChild(document.createTextNode('科系'));
		tr.cells[2].appendChild(document.createTextNode('編號'));
		table.appendChild(tr);

		for (var k = 0; k < favs.length; k++) {
			var tr = document.createElement('tr');
			for (var i = 0; i < 3; i++)
				tr.appendChild(document.createElement('th'));
			tr.cells[0].appendChild(document.createTextNode('x'));
			tr.cells[1].appendChild(document.createTextNode('x'));
			tr.cells[2].appendChild(document.createTextNode(favs[k]));
			table.appendChild(tr);
		}
	}
</script>
EOF;
	[$username, $type, $hash] = explode("-", $key, 3);
	$file = "storage/$username/$type-$hash.json";
	if (!file_exists($file)) {
		echo <<<EOF
<big style='color: red;'>查無此紀錄，請確認確認連結完整性</big>
<script>
	setTimeout(() => {
		location.href = '..';
	}, 3000);
</script>
EOF;
	} else {
		$json = file_get_contents($file);
		$favs = json_decode($json, true);

	}
}
?>
	</div>
</body>
</html>
